### ISSUE TITLE
IndexError: pop from an empty deque from _kernel_wake

### ISSUE THREAD

**Issue by mwerezak** [dabeaz/curio#365]
Got this exception from inside curio/sched.py

Not sure yet as to the cause.
```
Traceback (most recent call last):
  File "...", line 72, in <module>
    curio.run(main)
  File "...\venv\Lib\site-packages\curio\kernel.py", line 824, in run
    return kernel.run(corofunc, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\curio\kernel.py", line 146, in run
    task = self._runner(coro)
           ^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\curio\kernel.py", line 768, in kernel_run
    traps[trap[0]](*trap[1:])
  File "...\venv\Lib\site-packages\curio\kernel.py", line 519, in trap_sched_wake
    tasks = sched._kernel_wake(n)
            ^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\curio\sched.py", line 88, in _kernel_wake
    task, = self._queue.popleft()
            ^^^^^^^^^^^^^^^^^^^^^
IndexError: pop from an empty deque
```

**Comment by mwerezak** [comment]
I have no idea where to even start looking for the cause of this. Any insight would be appreciated.

**Comment by mwerezak** [comment]
It seems related to creating a lot of timeouts using `curio.timeout_after()`

This appears to be the offending code:
```python
        async with self._condition:
            while not self._bus_available():
                try:
                    async with curio.timeout_after(self.wait_interval):
                        await self._condition.wait()
                except curio.TaskTimeout:
                    _log.debug(f"{client}: wait.")
                    await client.send_message(WAIT_MSG)
```

**Comment by dabeaz** [comment]
What version of curio?  What version of Python? What operating system?   Is the bug predictably reproducible or is it random?

**Comment by mwerezak** [comment]
Hi, my apologies for forgetting to include that information.

curio version 1.6
Python version 3.11.5

From memory the bug was pretty predictable but depended on workload... that snippet above was being hit ~10-100/second, with the timeout value being about 5 seconds IIRC... I guess that means several hundred timeouts active at once. Under lesser loads the bug did not manifest, but I don't recall the exact number.

We implemented a workaround by using frequent polling instead of blocking on a condition variable.

**Comment by x42005e1f** [comment]
The cause is actually quite simple. `SchedFIFO`, which is [used by `Condition`](https://github.com/dabeaz/curio/blob/92192cef307391f4ec0a5edc700906fb45cead4c/curio/sync.py#L297), [does not check the waiting queue length at all](https://github.com/dabeaz/curio/blob/70378d229f8e9265091a758688ef9d41609366d8/curio/sched.py#L87), and as a result `cond.notify()` tries to perform [`self._queue.popleft()`](https://github.com/dabeaz/curio/blob/70378d229f8e9265091a758688ef9d41609366d8/curio/sched.py#L88) for the empty queue, thus raising `IndexError`. Below is a fairly simple code that reproduces the issue.

```python
import curio


async def main():
    async with curio.Condition() as cond:
        await cond.notify()  # IndexError + RuntimeError


if __name__ == "__main__":
    curio.run(main)
```

The quickest solution is to add a check that the queue is not empty to the loop condition. Or add a check for `SchedFIFO` length to the `Condition` methods themselves in the [spirit of the other primitives](https://github.com/dabeaz/curio/blob/92192cef307391f4ec0a5edc700906fb45cead4c/curio/sync.py#L178), but this seems like an ugly solution to me, especially because of memory leaks on cancellations (1-item lists are [not removed](https://github.com/dabeaz/curio/blob/70378d229f8e9265091a758688ef9d41609366d8/curio/sched.py#L73-L75)).

**Comment by mwerezak** [comment]
I guess the question is, what should happen when you try notify a `SchedFIFO` that is empty? Does it make sense for the alert to become a no-op in that case?

**Comment by x42005e1f** [comment]
> Does it make sense for the alert to become a no-op in that case?

Almost correct. That is not an alert, but a bug that [causes Curio to die](https://github.com/dabeaz/curio/blob/751b0d313c25ac03d57f475c8aafa1fca6005785/curio/kernel.py#L762-L772). In the example shown, the output will look like this:

```python
Traceback (most recent call last):
  File "/home/user/workspace/test.py", line 10, in <module>
    curio.run(main)
  File "/home/user/.local/lib/python3.12/site-packages/curio/kernel.py", line 824, in run
    return kernel.run(corofunc, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/curio/kernel.py", line 146, in run
    task = self._runner(coro)
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/curio/kernel.py", line 768, in kernel_run
    traps[trap[0]](*trap[1:])
  File "/home/user/.local/lib/python3.12/site-packages/curio/kernel.py", line 519, in trap_sched_wake
    tasks = sched._kernel_wake(n)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/curio/sched.py", line 88, in _kernel_wake
    task, = self._queue.popleft()
            ^^^^^^^^^^^^^^^^^^^^^
IndexError: pop from an empty deque
Exception ignored in: <function Task.__del__ at 0x7ff187ebed40>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/curio/task.py", line 157, in __del__
  File "/home/user/.local/lib/python3.12/site-packages/curio/task.py", line 222, in exception
RuntimeError: Task not terminated
sys:1: ResourceWarning: unclosed <socket.socket fd=5, family=1, type=1, proto=0>
sys:1: ResourceWarning: unclosed <socket.socket fd=4, family=1, type=1, proto=0>
```

**Comment by mwerezak** [comment]
I think you misunderstood me. What you are talking about is an exception
that is raised, which is not what I meant by "alert".

By "alert" I was referring to the mechanism that causes a sleeping task to be woken up (I only chose that word because I saw it being used with a similar meaning in the comments for UniversalQueueBase).

The way SchedFIFO is written, it appears to expect every sleeping task (suspend) to be paired with an alert (wake).

Imagine now that due to concurrency a suspend/wake pair gets reordered such that the wake arrives before the suspend. Should the the wake be converted into a no-op because the queue is empty? Or should it wake the next suspended task to arrive?

I don't know because I don't have enough context. I don't know the
intention of SchedFIFO. I don't know all the situations in which it is
used. This is why I'm hoping for someone with more familiarity to join in the conversation.

**Comment by x42005e1f** [comment]
> I think you misunderstood me.

Yes, I misunderstood you, because you used the word "notify" in the previous sentence.

> Imagine now that due to concurrency a suspend/wake pair gets reordered such that the wake arrives before the suspend.

This is not true for Kernel code. We are dealing with coroutines (cooperative multitasking) rather than threads (preemptive multitasking). Therefore, we do not need to worry about waking up the next arrivals. Moreover, neither `asyncio.Condition` nor even `threading.Condition` do this.

If user code relies on such behavior, then it is simply using `Condition` incorrectly - it is not a primitive that counts the number of wakes like a semaphore or its friends. Calling `notify()` when there are no waiters is always expected to be a no-op.

**Comment by mwerezak** [comment]
Ok, good to know.
