### ISSUE TITLE
Multiple calls to curio.new_task() causes crash

### ISSUE THREAD

**Issue by roger-** [dabeaz/curio#37]
The following code seems to trigger this:

```python
import curio

async def go():
    await curio.sleep(2)
    
async def main():
    task1 = await curio.new_task(go())
    task2 = await curio.new_task(go()) 
    
if __name__ == '__main__':
    kernel = curio.Kernel()
    kernel.run(main())
```

Gives this:
```
Curio: Task Crash: go
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\curio\kernel.py", line 370, in run
    getattr(self, op)(current, *args)
  File "C:\Anaconda3\lib\site-packages\curio\kernel.py", line 477, in _trap_sleep
    self._set_timeout(current, seconds, 'sleep')
  File "C:\Anaconda3\lib\site-packages\curio\kernel.py", line 308, in _set_timeout
    heapq.heappush(self._sleeping, item)
TypeError: unorderable types: Task() < Task()
Traceback (most recent call last):
  File "C:\Users\roger\OneDrive\Documents\Python Scripts\delme.py", line 20, in <module>
    kernel.run(main())
  File "C:\Anaconda3\lib\site-packages\curio\kernel.py", line 355, in run
    self._poll_for_io()
  File "C:\Anaconda3\lib\site-packages\curio\kernel.py", line 334, in _poll_for_io
    self._reschedule_task(task)
  File "C:\Anaconda3\lib\site-packages\curio\kernel.py", line 234, in _reschedule_task
    assert task.id in self._tasks, 'Task %r not in the task table' % task
AssertionError: Task Task(id=4, <coroutine object go at 0x000000B1A98EA888>, state='CRASHED') not in the task table
```

**Comment by dabeaz** [comment]
Interesting.   This is not reproducible on my machine, but think it can be fixed by adding a few methods to Task to make them ordered.   Will make a patch shortly.

**Comment by dabeaz** [comment]
Fixed by including the task id in the sleep queue to break ties in heapq.
