### ISSUE TITLE
run function swallows all exceptions

### ISSUE THREAD

**Issue by Zaharid** [dabeaz/curio#53]
Consider:

````python
import curio
async def main():
    raise Exception("My function failed")
    return "Completed"
    

try:
    res = curio.run(main())
except:
    print("OK")
    raise
else:
    print("uh?")
print("Should not be here...")
#Since there was no exception:
assert(res=="Completed")
````

The exception will be printed to screen (with the log_errors option set to True), but will not be further raised up the stack and the return value will be None. 

Therefore the result I get is:
````
Curio: Task Crash: main
Traceback (most recent call last):
  File "/home/zah/sourcecode/curio/curio/kernel.py", line 562, in run
    trap = current._send(current.next_value)
  File "<ipython-input-2-2eb192ef26ea>", line 3, in main
    raise Exception("My function failed")
Exception: My function failed
uh?
Should not be here...
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-2eb192ef26ea> in <module>()
     14 print("Should not be here...")
     15 #Since there was no exception:
---> 16 assert(res=="Completed")

AssertionError: 
````

And I would expect to deal either with my original exception or a with TaskError.

**Comment by dabeaz** [comment]
Indeed it doesn't report the error.  Now fixed in Github.   Thanks for finding this!

**Comment by Zaharid** [comment]
Great, working now. Thanks!
