### ISSUE TITLE
Remote exception does not point to the line that caused the exception

### ISSUE THREAD

**Issue by Zaharid** [dabeaz/curio#55]
The traceback of:

````
import curio

def f(x):
    raise ValueError("Hello")
    return x

async def main():
    await curio.run_in_process(f,5)
    return "Completed"
    

try:
    res = curio.run(main())
except curio.TaskError as e:
    raise
````

does not show the line inside the `f` function where the exception occurred:

````
ValueError                                Traceback (most recent call last)
/home/zah/sourcecode/curio/curio/kernel.py in run(self, coro, shutdown)
    561                     if current.next_exc is None:
--> 562                         trap = current._send(current.next_value)
    563                     else:

<ipython-input-30-e4e29ac70d40> in main()
      7 async def main():
----> 8     await curio.run_in_process(f,5)
      9     return "Completed"

/home/zah/sourcecode/curio/curio/workers.py in run_in_process(callable, *args, **kwargs)
     81 
---> 82     return await kernel._process_pool.apply(callable, args, kwargs)
     83 

/home/zah/sourcecode/curio/curio/workers.py in apply(self, func, args, kwargs)
    249             try:
--> 250                 return await worker.apply(func, args, kwargs)
    251             except CancelledError:

/home/zah/sourcecode/curio/curio/workers.py in apply(self, func, args, kwargs)
    220         else:
--> 221             raise result
    222 

ValueError: Hello

The above exception was the direct cause of the following exception:

TaskError                                 Traceback (most recent call last)
<ipython-input-30-e4e29ac70d40> in <module>()
     14 except curio.TaskError as e:
     15     print(type(e.__cause__))
---> 16     raise e

<ipython-input-30-e4e29ac70d40> in <module>()
     11 
     12 try:
---> 13     res = curio.run(main())
     14 except curio.TaskError as e:
     15     print(type(e.__cause__))

/home/zah/sourcecode/curio/curio/kernel.py in run(coro, pdb, log_errors, with_monitor, selector)
    648     kernel = Kernel(selector=selector, with_monitor=with_monitor,
    649                     log_errors=log_errors, pdb=pdb)
--> 650     result = kernel.run(coro, shutdown=True)
    651     return result
    652 

/home/zah/sourcecode/curio/curio/kernel.py in run(self, coro, shutdown)
    627         if maintask:
    628             if maintask.next_exc:
--> 629                 raise maintask.next_exc
    630             else:
    631                 return maintask.next_value

TaskError: Task Crashed
````

This is shown with multiprocessing alone:

````
import multiprocessing
p = multiprocessing.Pool()
p.apply(f, (1,))
````

shows a "RemoteTraceback"

````
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zah/anaconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "<ipython-input-30-e4e29ac70d40>", line 4, in f
    raise ValueError("Hello")
ValueError: Hello
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-31-9ccf31c9442a> in <module>()
      1 import multiprocessing
      2 p = multiprocessing.Pool()
----> 3 p.apply(f, (1,))

/home/zah/anaconda3/lib/python3.5/multiprocessing/pool.py in apply(self, func, args, kwds)
    251         '''
    252         assert self._state == RUN
--> 253         return self.apply_async(func, args, kwds).get()
    254 
    255     def map(self, func, iterable, chunksize=None):

/home/zah/anaconda3/lib/python3.5/multiprocessing/pool.py in get(self, timeout)
    606             return self._value
    607         else:
--> 608             raise self._value
    609 
    610     def _set(self, i, obj):

ValueError: Hello
````

**Comment by dabeaz** [comment]
Did some digging into this.  I think I can take a similar approach in Curio, but the result is going to add a third level of traceback to the result.   The immediate error would be a TaskError.  The cause of that would be the actual exception that was raised (same as now).  Then, the cause of that error would be RemoteTraceback exception as is done in multiprocessing.    The resulting traceback would probably look pretty hairy, but it would show the offending source line somewhere in the fray.

**Comment by dabeaz** [comment]
Pushed a fix that adds this. I just copied the exception wrapping code from multiprocessing.pool.

**Comment by Zaharid** [comment]
Thanks. Works fine for me!
